version : '3.9'
services:
    api:
        build: ./api/
        hostname: api
        environment:
          - API_HOST=${API_HOST}
      
        volumes:
          - ./api/code:/app
        ports:
          # - "0.0.0.0:5000:5000"
          #- "5002:5002"
          - "5000:5000"
    consumer:
        build: ./consumer/
        hostname: consumer
        environment:
          - API_HOST = {API_HOST}
          - API_PORT = {API_PORT}
          - API_ENDPOINT = {API_ENDPOINT}
          - CONSUMER_PORT = {CONSUMER_PORT}
        volumes:
          - ./consumer/code:/app
        ports:
           - "80:80"
          #- "0.0.0.0.80:80"